config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                             Controller#Action
#                     root GET    /                                       static_pages#home
#                 products GET    /products(.:format)                     products#index
#                          POST   /products(.:format)                     products#create
#              new_product GET    /products/new(.:format)                 products#new
#             edit_product GET    /products/:product_id/edit(.:format)    products#edit
#                  product PATCH  /products/:product_id(.:format)         products#update
#                          PUT    /products/:product_id(.:format)         products#update
#                          DELETE /products/:product_id(.:format)         products#destroy
#               categories GET    /categories(.:format)                   categories#index
#                          POST   /categories(.:format)                   categories#create
#             new_category GET    /categories/new(.:format)               categories#new
#            edit_category GET    /categories/:category_id/edit(.:format) categories#edit
#                 category PATCH  /categories/:category_id(.:format)      categories#update
#                          PUT    /categories/:category_id(.:format)      categories#update
#                          DELETE /categories/:category_id(.:format)      categories#destroy
#                     cart GET    /cart(.:format)                         cart#show
#              add_to_cart POST   /add_to_cart(.:format)                  cart#add
#         remove_from_cart GET    /remove_from_cart(.:format)             cart#remove
#                    login GET    /login(.:format)                        sessions#new
#                          GET    /auth/:provider/callback(.:format)      sessions#create
#                   logout GET    /logout(.:format)                       sessions#destroy
#            mobile_number GET    /mobile_number(.:format)                mobile_number#new
#   mobile_number_send_otp POST   /mobile_number/send_otp(.:format)       mobile_number#send_otp
# mobile_number_verify_otp POST   /mobile_number/verify_otp(.:format)     mobile_number#verify_otp
#                 checkout GET    /checkout(.:format)                     orders#new
#                thank_you GET    /thank_you(.:format)                    orders#show
#              place_order POST   /place_order(.:format)                  orders#create
#

Rails.application.routes.draw do
  root 'static_pages#home'
  resources :products, except: :show, param: :product_id
  resources :categories, except: :show, param: :category_id

  get 'cart', to: 'cart#show'
  post :add_to_cart, to: 'cart#add'
  get :remove_from_cart, to: 'cart#remove'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'mobile_number', to: 'mobile_number#new'
  post 'mobile_number/send_otp', to: 'mobile_number#send_otp'
  post 'mobile_number/verify_otp', to: 'mobile_number#verify_otp'

  get 'checkout', to: 'orders#new'
  get 'thank_you', to: 'orders#show'
  post 'place_order', to: 'orders#create'

  post 'contact_us', to: 'contact_us#send_message'

  # get 'menu_card', to: 'static_pages#menu_card'
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    layout false

    def show
       @cart = get_or_create_shopping_cart
       @line_item = @cart.line_items
    end

    def add
        @cart = get_or_create_shopping_cart
        @cart.add(params[:product_id], params[:quantity])
        flash[:notice] = "The item is now in your cart."
        redirect_to :back or products_url
    end

    def remove
       @cart = get_or_create_shopping_cart
       @cart.remove(params[:line_item_id])
       flash[:notice] = "Item removed from cart."
       redirect_to :back or cart_url
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/show.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/partials/head', specific_css_file_link: capture { %>
  <link rel="stylesheet" type="text/css" href="css/shopping_cart.css">
<% } %>
  <body id="cartpage">
    <%= render 'cart/show_partials/navbar', right_side_menu: false %>
    <%= render partial: "layouts/partials/flash", flash: flash %>
    <div class="container-fluid" style="background-color:#f3f2f2">
      <div class="container">
      <h2 id="table_header">My Shopping cart</h2>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>Sr.No</th>
            <th>Name</th>
            <th>Price/cake</th>
            <th>Quantity</th>
            <th>Weight</th>
            <th>Total</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody>
          <% @cart.line_items.each_with_index do |line_item, idx| %>
            <tr>
              <th class="sr_no" scope="row"><%= 1+idx %></th>
              <td class="cart_img"><img src="<%= line_item.product.image.url %>" alt="" class="img-rounded cart_cake_img">Mark</td>

              <td class="cart_unitprice">Rs. <%= line_item.unit_price %></td>
              <td class="cake_qty"><%= line_item.quantity %></td>
              <td class="cart_qty_col"><%= line_item.product.weight %> Kg
              </td>
              <td class="cart_total">Rs. <%= line_item.total %></td>
              <td class="cart_remove_btn"><a class="btn btn-danger" href="<%= remove_from_cart_path(line_item_id: line_item.id) %>"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
            </tr>
          <% end %>
          <tr class="alert alert-info">
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>NET TOTAL</td>
            <td>Rs.<%= @cart.total %>/-</td>
          </tr>
        </tbody>
     </table>

     <div class="row" id="cart_btn">
       <div class="col-md-4">
         <a href="<%= products_path %>"><button type="button" name="button" class="btn pull-left" id="cart_back" style="font-size:bold">Back to shopping</button></a>
       </div>
       <div class="col-md-4"></div>
       <div class="col-md-4">
         <a href="<%= checkout_path %>"><button type="button" name="button" class="btn pull-right" id="cart_checkout">Checkout</button></a>
       </div>
     </div>
     </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!--<script src="js/bootstrap3.min.js"></script>-->
    <script src="js/jquery.min.js"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>-->
    <script src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/script.js"></script>
  </body>
</html>