config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                             Controller#Action
#                     root GET    /                                       static_pages#home
#                 products GET    /products(.:format)                     products#index
#                          POST   /products(.:format)                     products#create
#              new_product GET    /products/new(.:format)                 products#new
#             edit_product GET    /products/:product_id/edit(.:format)    products#edit
#                  product PATCH  /products/:product_id(.:format)         products#update
#                          PUT    /products/:product_id(.:format)         products#update
#                          DELETE /products/:product_id(.:format)         products#destroy
#               categories GET    /categories(.:format)                   categories#index
#                          POST   /categories(.:format)                   categories#create
#             new_category GET    /categories/new(.:format)               categories#new
#            edit_category GET    /categories/:category_id/edit(.:format) categories#edit
#                 category PATCH  /categories/:category_id(.:format)      categories#update
#                          PUT    /categories/:category_id(.:format)      categories#update
#                          DELETE /categories/:category_id(.:format)      categories#destroy
#                     cart GET    /cart(.:format)                         cart#show
#              add_to_cart POST   /add_to_cart(.:format)                  cart#add
#         remove_from_cart GET    /remove_from_cart(.:format)             cart#remove
#                    login GET    /login(.:format)                        sessions#new
#                          GET    /auth/:provider/callback(.:format)      sessions#create
#                   logout GET    /logout(.:format)                       sessions#destroy
#            mobile_number GET    /mobile_number(.:format)                mobile_number#new
#   mobile_number_send_otp POST   /mobile_number/send_otp(.:format)       mobile_number#send_otp
# mobile_number_verify_otp POST   /mobile_number/verify_otp(.:format)     mobile_number#verify_otp
#                 checkout GET    /checkout(.:format)                     orders#new
#                thank_you GET    /thank_you(.:format)                    orders#show
#              place_order POST   /place_order(.:format)                  orders#create
#

Rails.application.routes.draw do
  root 'static_pages#home'
  resources :products, except: :show, param: :product_id
  resources :categories, except: :show, param: :category_id

  get 'cart', to: 'cart#show'
  post :add_to_cart, to: 'cart#add'
  get :remove_from_cart, to: 'cart#remove'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'mobile_number', to: 'mobile_number#new'
  post 'mobile_number/send_otp', to: 'mobile_number#send_otp'
  post 'mobile_number/verify_otp', to: 'mobile_number#verify_otp'

  get 'checkout', to: 'orders#new'
  get 'thank_you', to: 'orders#show'
  post 'place_order', to: 'orders#create'

  post 'contact_us', to: 'contact_us#send_message'

  # get 'menu_card', to: 'static_pages#menu_card'
end

app/controllers/mobile_number_controller.rb
class MobileNumberController < ApplicationController
  layout false

  def new
  end

  def send_otp
    # TODO
    number = Random.rand(100000..1000000)
    current_user.mobile_number = params[:mobile_number]
    current_user.otp = number
    current_user.save
    render json: { otp: number }
  end

  def verify_otp
    if params[:otp] and params[:otp] == current_user.otp
      current_user.otp = nil
      current_user.otp_verified = true
      current_user.save
      flash[:notice] = "Your number has been successfully verified."
      redirect_to products_url
    else
      flash[:error] = "Your number could not be successfully verified. Please try again."
      redirect_to mobile_number_url
    end
  end

end

app/helpers/mobile_number_helper.rb
module MobileNumberHelper
end

app/views/mobile_number/new.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/partials/head', specific_css_file_link: capture { %>
    <link rel="stylesheet" type="text/css" href="css/styles_otp.css">
  <% } %>
  <% # do end syntax doesn't work in the above %>

  <body id="otp_page">
    <%= render 'layouts/partials/navbar', right_side_menu: false %>
    <%= render partial: "layouts/partials/flash", flash: flash %>

  <!--====otp page start=====-->

  <div class="container" style="margin-bottom:50px;">
    <div class="page-header">
      <h3 style="text-align:center; font-weight:bold; margin-top:100px">All set...Go!</h2>
      <p style="text-align:center">We need your mobile number to get in touch with you!</p>
    </div>
    <hr class="style2" style="margin-bottom:50px">
    <div class="row" style="background-color:#eaebed">
      <div class="col-sm-4"></div>

      <div class="col-sm-6 col-sm-border">
        <h4 style="font-weight:bold; margin-top:30px">Verify your mobile</h4>
        <hr>
        <form id="enter_mobile_number" action="" method="POST">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
					<div class="form-group">
            <div class="row">
              <label class="col-md-5 col-form-label" style="font-size:13px">Enter mobile number</label>
              <div class="col-md-7"></div>
            </div>
            <div class="row">
                <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-8">
                      <input type="text" class="form-control form-control-sm" placeholder="" name="mobile_number">
                    </div>
                    <div class="col-md-4">
                      <button id="mobile_number_submit" class="btn btn-danger btn-sm finish_login_btn" type="submit" name="" style="margin-top:2px">send OTP</button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6"></div>
              </div>
            </div>
        </form>
        <form id="enter_otp" action=<%= mobile_number_verify_otp_path %> method="POST">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group">
              <div class="row">
                <label class="col-md-5 col-form-label" style="font-size:13px">Enter OTP here</label>
                <div class="col-md-7"></div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-7">
                      <input type="tel" name="otp" class="form-control form-control-sm" placeholder="" maxlength="6">
                    </div>
                    <div class="col-md-5">
                      <button class="btn btn-danger btn-sm finish_login_btn" type="submit" name="" style="margin-top:2px">Verify</button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6"></div>
              </div>
      			</div>
          </form>
        </div>
        <div class="col-sm-2"></div>
    </div>
  </div>

  <!--====otp page end=====-->

  <%= render 'layouts/partials/footer' %>

  <%= render 'layouts/partials/javascripts', specific_js_file_link: capture { %>
    <script type="text/javascript" src="js/mobile_number.js"></script>
  <% } %>

  </body>
</html>