config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                             Controller#Action
#                     root GET    /                                       static_pages#home
#                 products GET    /products(.:format)                     products#index
#                          POST   /products(.:format)                     products#create
#              new_product GET    /products/new(.:format)                 products#new
#             edit_product GET    /products/:product_id/edit(.:format)    products#edit
#                  product PATCH  /products/:product_id(.:format)         products#update
#                          PUT    /products/:product_id(.:format)         products#update
#                          DELETE /products/:product_id(.:format)         products#destroy
#               categories GET    /categories(.:format)                   categories#index
#                          POST   /categories(.:format)                   categories#create
#             new_category GET    /categories/new(.:format)               categories#new
#            edit_category GET    /categories/:category_id/edit(.:format) categories#edit
#                 category PATCH  /categories/:category_id(.:format)      categories#update
#                          PUT    /categories/:category_id(.:format)      categories#update
#                          DELETE /categories/:category_id(.:format)      categories#destroy
#                     cart GET    /cart(.:format)                         cart#show
#              add_to_cart POST   /add_to_cart(.:format)                  cart#add
#         remove_from_cart GET    /remove_from_cart(.:format)             cart#remove
#                    login GET    /login(.:format)                        sessions#new
#                          GET    /auth/:provider/callback(.:format)      sessions#create
#                   logout GET    /logout(.:format)                       sessions#destroy
#            mobile_number GET    /mobile_number(.:format)                mobile_number#new
#   mobile_number_send_otp POST   /mobile_number/send_otp(.:format)       mobile_number#send_otp
# mobile_number_verify_otp POST   /mobile_number/verify_otp(.:format)     mobile_number#verify_otp
#                 checkout GET    /checkout(.:format)                     orders#new
#                thank_you GET    /thank_you(.:format)                    orders#show
#              place_order POST   /place_order(.:format)                  orders#create
#

Rails.application.routes.draw do
  root 'static_pages#home'
  resources :products, except: :show, param: :product_id
  resources :categories, except: :show, param: :category_id

  get 'cart', to: 'cart#show'
  post :add_to_cart, to: 'cart#add'
  get :remove_from_cart, to: 'cart#remove'

  get 'login', to: 'sessions#new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'mobile_number', to: 'mobile_number#new'
  post 'mobile_number/send_otp', to: 'mobile_number#send_otp'
  post 'mobile_number/verify_otp', to: 'mobile_number#verify_otp'

  get 'checkout', to: 'orders#new'
  get 'thank_you', to: 'orders#show'
  post 'place_order', to: 'orders#create'

  post 'contact_us', to: 'contact_us#send_message'

  # get 'menu_card', to: 'static_pages#menu_card'
end

app/views/layouts/partials/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/layouts/partials/_head.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Redgini | love in every bite</title>

	<!--Bootstrap CSS-->
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<%= specific_css_file_link %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

app/views/layouts/partials/_javascripts.html.erb
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<!--<script src="js/bootstrap3.min.js"></script>-->
<script src="js/jquery.min.js"></script>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>-->
<script src="js/bootstrap.min.js"></script>
<%= specific_js_file_link %>

app/views/layouts/partials/_navbar.html.erb
<!-- ===================Navbar start============================ -->
<nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top" id="homepageNavbar">
  	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar_main" aria-controls="navbar_main" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  	</button>
  	<a class="navbar-brand" href=<%= root_path %> id="brand_name">Redgini</a>

  <div class="collapse navbar-collapse" id="navbar_main">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0" id="navbar_items">
      <li class="nav-item">
        <a class="nav-link" href=<%= root_path %>>Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#aboutus">About us</a>
      </li>
			<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
					data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-content" aria-labelledby="navbarDropdownMenuLink" id="products_dropdown">
          <a class="dropdown-item" href=<%= products_path %>>Cakes & Pastry</a>
        </div>
      </li>
        <a class="nav-link" href="#">Our team</a>
      </li>
		</ul>

  </div>

  <% if right_side_menu %>
  	<a href=<%= cart_path %> id="shop_cart_home"><i class="fa fa-shopping-cart fa-2x  hidden-sm-down" aria-hidden="true" id="shop_cart_home_icon"></i></a>
  	<a class="btn btn-danger pull-right btn-sm hidden-sm-up" href="shopping_cart.html" id="cart_navbar"  data-toggle="" data-target="">
  	Shopping cart</a>

    <% if !logged_in? %>
  	 <a class="btn btn-danger pull-right btn-sm" href=<%= login_path %> id="signIn_navbar"  data-toggle="" data-target="">
  	Signup/Login</a>
    <% end %>
  <% end %>
</nav>

app/views/layouts/partials/_navbar_without_menu.html.erb
<!--=======navbar for the product page start=========-->
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand">
    <strong>Redgini</strong>
  </a>
  <div class="collapse navbar-collapse" id="">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <p class="navbar_lines"><i class="fa fa-check" aria-hidden="true"></i> 100% Genuine & fresh Products</p>
      </li>
      <li class="nav-item">
        <p class="navbar_lines"><i class="fa fa-shield" aria-hidden="true"></i> Secure Payments</p>
      </li>
      <li class="nav-item">
        <p class="navbar_lines"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Free delivery</p>
      </li>
    </ul>
  </div>
  <% if right_side_menu %>
    <a href=<%= cart_path %> id="shop_cart_home" class="pull-right"><i class="fa fa-shopping-cart fa-2x hidden-sm-down" aria-hidden="true" id="shop_cart_home_icon"></i></a>
    <a class="btn btn-danger pull-right btn-sm hidden-sm-up" href=<%= cart_path %> id="cart_navbar"  data-toggle="" data-target="">
  Shopping cart</a>
    <% if !logged_in? %>
      <a class="btn btn-sm pull-right" href="#" id="signIn_navbar">Signup/Login</a>
    <% end %>
  <% end %>
</nav>
<!--=======navbar for the product page end=========-->